In [98]:
import pandas as pd
import numpy as np

In [99]:
df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
satisfaction_level       14999 non-null float64
last_evaluation          14999 non-null float64
number_project           14999 non-null int64
average_montly_hours     14999 non-null int64
time_spend_company       14999 non-null int64
Work_accident            14999 non-null int64
left                     14999 non-null int64
promotion_last_5years    14999 non-null int64
department               14999 non-null object
salary                   14999 non-null object
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [101]:
df.describe()

satisfaction_level  last_evaluation  number_project  \
count        14999.000000     14999.000000    14999.000000   
mean             0.612834         0.716102        3.803054   
std              0.248631         0.171169        1.232592   
min              0.090000         0.360000        2.000000   
25%              0.440000         0.560000        3.000000   
50%              0.640000         0.720000        4.000000   
75%              0.820000         0.870000        5.000000   
max              1.000000         1.000000        7.000000   

       average_montly_hours  time_spend_company  Work_accident          left  \
count          14999.000000        14999.000000   14999.000000  14999.000000   
mean             201.050337            3.498233       0.144610      0.238083   
std               49.943099            1.460136       0.351719      0.425924   
min               96.000000            2.000000       0.000000      0.000000   
25%              156.000000            3.000000       0.000000      0.000000   
50%              200.000000            3.000000       0.000000      0.000000   
75%              245.000000            4.000000       0.000000      0.000000   
max              310.000000           10.000000       1.000000      1.000000   

       promotion_last_5years  
count           14999.000000  
mean                0.021268  
std                 0.144281  
min                 0.000000  
25%                 0.000000  
50%                 0.000000  
75%                 0.000000  
max                 1.000000

### Convert the categorical(department, salary) columns to numbers ###

In [102]:
cat = ['department','salary']
df_mod = pd.get_dummies(df,columns=cat, drop_first=True)

In [103]:
df_mod.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  \
0                   3              0     1                      0   
1                   6              0     1                      0   
2                   4              0     1                      0   
3                   5              0     1                      0   
4                   3              0     1                      0   

   department_RandD  department_accounting  department_hr  \
0                 0                      0              0   
1                 0                      0              0   
2                 0                      0              0   
3                 0                      0              0   
4                 0                      0              0   

   department_management  department_marketing  department_product_mng  \
0                      0                     0                       0   
1                      0                     0                       0   
2                      0                     0                       0   
3                      0                     0                       0   
4                      0                     0                       0   

   department_sales  department_support  department_technical  salary_low  \
0                 1                   0                     0           1   
1                 1                   0                     0           0   
2                 1                   0                     0           0   
3                 1                   0                     0           1   
4                 1                   0                     0           1   

   salary_medium  
0              0  
1              1  
2              1  
3              0  
4              0

In [104]:
len(df_mod.columns)

19

### Spliting the training set ###

In [105]:
from sklearn.model_selection import train_test_split

In [106]:
X = df_mod.drop(['left'],axis=1).values
y = df_mod['left'].values

In [107]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

### Since features that have different measurements,transform the values to have a mean of 0 and a standard deviation of 1###

In [108]:
from sklearn.preprocessing import StandardScaler

In [109]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Building the deep learning model

In [110]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [111]:
clf  = Sequential()

In [112]:
clf.add(Dense(9,kernel_initializer="uniform",activation="relu",input_dim=18))

In [113]:
clf.add(Dense(1,kernel_initializer="uniform",activation="sigmoid"))

In [114]:
clf.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [115]:
clf.fit(X_train,y_train,batch_size=10,epochs=10)

Epoch 1/10
10499/10499 [==============================] - 3s 309us/step - loss: 0.4231 - acc: 0.7926
Epoch 2/10
10499/10499 [==============================] - 2s 225us/step - loss: 0.2705 - acc: 0.8490
Epoch 3/10
10499/10499 [==============================] - 2s 226us/step - loss: 0.2286 - acc: 0.9359
Epoch 4/10
10499/10499 [==============================] - 2s 230us/step - loss: 0.2066 - acc: 0.9486
Epoch 5/10
10499/10499 [==============================] - 2s 227us/step - loss: 0.1932 - acc: 0.9541
Epoch 6/10
10499/10499 [==============================] - 2s 225us/step - loss: 0.1845 - acc: 0.9543
Epoch 7/10
10499/10499 [==============================] - 2s 225us/step - loss: 0.1783 - acc: 0.9535
Epoch 8/10
10499/10499 [==============================] - 2s 229us/step - loss: 0.1749 - acc: 0.9550
Epoch 9/10
10499/10499 [==============================] - 2s 228us/step - loss: 0.1716 - acc: 0.9548
Epoch 10/10
10499/10499 [==============================] - 2s 226us/step - loss: 0.1696 - a

### Predicition ###

In [116]:
y_pred = clf.predict(X_test)

In [117]:
y_pred = (y_pred > 0.5)

### Evaluation metrics ##

In [118]:
from sklearn.metrics import confusion_matrix

In [119]:
confusion_mat = confusion_matrix(y_test,y_pred)

In [120]:
confusion_mat

array([[3334,  101],
       [ 104,  961]], dtype=int64)

In [121]:
# making a new prediction(single)
new_prediction = clf.predict(sc.transform(np.array([[0.26,0.7 ,3., 238., 6., 0.,0.,0.,0., 0.,0.,0.,0.,0.,1.,0., 0.,1.]])))

In [122]:
new_prediction

array([[0.0190007]], dtype=float32)

In [123]:
new_prediction = (new_prediction > 0.5)
new_prediction

array([[False]])

### Improving the Model Accuracy- use k fold ###

In [124]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [125]:
def imp_clf():
    clf = Sequential()
    clf.add(Dense(9,kernel_initializer="uniform",activation="relu",input_dim=18))
    clf.add(Dense(1,kernel_initializer="uniform",activation="sigmoid"))
    clf.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
    return clf

In [134]:
clf = KerasClassifier(build_fn=imp_clf,batch_size=10,nb_epoch=10)

In [135]:
acc = cross_val_score(estimator=clf,X=X_train,y=y_train,cv=10,n_jobs=-1)

In [136]:
mean  = acc.mean()
mean

0.8443650594166439

In [137]:
var = acc.var()
var

0.0031261943715461963

### adding drop out layer to reduce overfitting ###

In [139]:
from keras.layers import Dropout

clf = Sequential()
clf.add(Dense(9, kernel_initializer = "uniform", activation = "relu", input_dim=18))
clf.add(Dropout(rate = 0.1))
clf.add(Dense(1, kernel_initializer = "uniform", activation = "sigmoid"))
clf.compile(optimizer= "adam",loss = "binary_crossentropy",metrics = ["accuracy"])

In [140]:
clf.fit(X_train,y_train,batch_size=10,epochs=10)

Epoch 1/10
10499/10499 [==============================] - 4s 395us/step - loss: 0.4510 - acc: 0.7601
Epoch 2/10
10499/10499 [==============================] - 3s 283us/step - loss: 0.3352 - acc: 0.8236
Epoch 3/10
10499/10499 [==============================] - 3s 276us/step - loss: 0.2987 - acc: 0.8940
Epoch 4/10
10499/10499 [==============================] - 3s 261us/step - loss: 0.2763 - acc: 0.9101
Epoch 5/10
10499/10499 [==============================] - 3s 275us/step - loss: 0.2615 - acc: 0.9158
Epoch 6/10
10499/10499 [==============================] - 3s 280us/step - loss: 0.2511 - acc: 0.9194
Epoch 7/10
10499/10499 [==============================] - 3s 288us/step - loss: 0.2435 - acc: 0.9213
Epoch 8/10
10499/10499 [==============================] - 3s 267us/step - loss: 0.2344 - acc: 0.9256
Epoch 9/10
10499/10499 [==============================] - 3s 258us/step - loss: 0.2309 - acc: 0.9254
Epoch 10/10
10499/10499 [==============================] - 3s 265us/step - loss: 0.2284 - a

### Hyperparameter tuning###

In [141]:
from sklearn.model_selection import GridSearchCV
def make_classifier(optimizer):
    clf = Sequential()
    clf.add(Dense(9, kernel_initializer = "uniform", activation = "relu", input_dim=18))
    clf.add(Dense(1, kernel_initializer = "uniform", activation = "sigmoid"))
    clf.compile(optimizer= optimizer,loss = "binary_crossentropy",metrics = ["accuracy"])
    return clf

In [142]:
clf = KerasClassifier(build_fn = make_classifier)

In [145]:
params = {
    'batch_size':[20,35],
    'epochs':[2,3],
    'optimizer':['adam','rmsprop']
}

In [149]:
grid_search = GridSearchCV(estimator=clf,
                           param_grid=params,
                           scoring="accuracy",
                           cv=2)

In [150]:
grid_search = grid_search.fit(X_train,y_train)

Epoch 1/2
5249/5249 [==============================] - 2s 339us/step - loss: 0.5776 - acc: 0.7603
Epoch 2/2
5249/5249 [==============================] - 1s 128us/step - loss: 0.3969 - acc: 0.7992
Epoch 1/2
5250/5250 [==============================] - 2s 350us/step - loss: 0.5989 - acc: 0.7493
Epoch 2/2
5250/5250 [==============================] - 1s 155us/step - loss: 0.4230 - acc: 0.7912
Epoch 1/2
5249/5249 [==============================] - 2s 340us/step - loss: 0.5839 - acc: 0.7643
Epoch 2/2
5249/5249 [==============================] - 1s 107us/step - loss: 0.4236 - acc: 0.7702
Epoch 1/2
5250/5250 [==============================] - 2s 352us/step - loss: 0.5980 - acc: 0.7560
Epoch 2/2
5250/5250 [==============================] - 1s 180us/step - loss: 0.4297 - acc: 0.7865
Epoch 1/3
5249/5249 [==============================] - 2s 355us/step - loss: 0.5860 - acc: 0.7603
Epoch 2/3
5249/5249 [==============================] - 1s 138us/step - loss: 0.3966 - acc: 0.8148
Epoch 3/3
5249/5249 

In [151]:
best_param = grid_search.best_params_
best_accuracy = grid_search.best_score_

In [152]:
best_param

{'batch_size': 20, 'epochs': 3, 'optimizer': 'adam'}

In [153]:
best_accuracy

0.8512239260881989